module INPUT.Test.Files.CodeGenTest.Hydra.Geometry.Pixelate where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: geometry. Family :: pixelate.

[[ : geometry : pixelate :: <what:Texture {EMP T} -> pixelX:Value {N 20.0} -> pixelY:Value {N 20.0}> => out:Texture {EMP T} /-| out::HYDRA.Geometry <what> $ HYDRA.GPixelate { <pixelX>, <pixelY> } |-/ ]] (#23) -}

_pixelate :: NId.Family "pixelate"
_pixelate = NId.Family

type Inlets =
  (I "what" Hot HYDRA.Texture :> I "pixelX" Hot HYDRA.Value :> I "pixelY" Hot HYDRA.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HYDRA.Texture, pixelX :: HYDRA.Value, pixelY :: HYDRA.Value)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "pixelate" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "pixelate" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "pixelate" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HYDRA.Empty, pixelX: HYDRA.Number 20.0, pixelY: HYDRA.Number 20.0 }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_pixelX = Noodle.Inlet :: _ "pixelX"
_in_pixelY = Noodle.Inlet :: _ "pixelY"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _pixelate defaultSt (Noodle.Shape :: Shape) defaultI defaultO pixelateP

makeNode :: Effect Node
makeNode = Family.spawn family

pixelateP :: Process
pixelateP = do
  what <- Fn.receive _in_what
  pixelX <- Fn.receive _in_pixelX
  pixelY <- Fn.receive _in_pixelY
  Fn.send _out_out $ HYDRA.Geometry what $ HYDRA.GPixelate { pixelX, pixelY }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
