module Test.Files.CodeGenTest.Hydra.Geometry.RepeatY where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. Group :: geometry. Family :: repeatY.

[[ : geometry : repeatY :: <what:Texture {EMP T} -> reps:Value {N 3.0} -> offset:Value {N 0.0}> => out:Texture {EMP T} /-| out::HT.Geometry <what> $ HT.GRepeatY { <reps>, <offset> } |-/ ]]

Toolkit : Hydra. File: ./src/Hydra/hydra.v0.3.ndf -}

_repeatY :: NId.Family "repeatY"
_repeatY = NId.Family

type Inlets =
  (I "what" Hot HT.Texture :> I "reps" Hot HT.Value :> I "offset" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, reps :: HT.Value, offset :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "repeatY" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "repeatY" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "repeatY" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, reps: HT.Number 3.0, offset: HT.Number 0.0 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_reps = Noodle.Inlet :: _ "reps"
_in_offset = Noodle.Inlet :: _ "offset"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _repeatY (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO repeatYP

makeNode :: Effect Node
makeNode = Family.spawn family

repeatYP :: Process
repeatYP = do
  what <- Fn.receive _in_what
  reps <- Fn.receive _in_reps
  offset <- Fn.receive _in_offset
  Fn.send _out_out $ HT.Geometry what $ HT.GRepeatY { reps, offset }
