module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Geometry.RepeatX where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: geometry. Family :: repeatX.

[[ : geometry : repeatX :: <what:Texture {EMP T} -> reps:Value {N 3.0} -> offset:Value {N 0.0}> => out:Texture {EMP T} /-| out::HYDRA.Geometry <what> $ HYDRA.GRepeatX { <reps>, <offset> } |-/ ]] (#25) -}

_repeatX :: NId.Family "repeatX"
_repeatX = NId.Family

type Inlets =
  (I "what" Hot HYDRA.Texture :> I "reps" Hot HYDRA.Value :> I "offset" Hot HYDRA.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HYDRA.Texture, reps :: HYDRA.Value, offset :: HYDRA.Value)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "repeatX" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "repeatX" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "repeatX" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HYDRA.Empty, reps: HYDRA.Number 3.0, offset: HYDRA.Number 0.0 }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_reps = Noodle.Inlet :: _ "reps"
_in_offset = Noodle.Inlet :: _ "offset"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _repeatX defaultSt (Noodle.Shape :: Shape) defaultI defaultO repeatXP

makeNode :: Effect Node
makeNode = Family.spawn family

repeatXP :: Process
repeatXP = do
  what <- Fn.receive _in_what
  reps <- Fn.receive _in_reps
  offset <- Fn.receive _in_offset
  Fn.send _out_out $ HYDRA.Geometry what $ HYDRA.GRepeatX { reps, offset }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
