module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Geometry.Rotate where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: geometry. Family :: rotate.

[[ : geometry : rotate :: <what:Texture {EMP T} -> angle:Value {N 10.0} -> speed:Value {N 1.0}> => out:Texture {EMP T} /-| out::HYDRA.Geometry <what> $ HYDRA.GRotate { <angle>, <speed> } |-/ ]] (#21) -}

_rotate :: NId.Family "rotate"
_rotate = NId.Family

type Inlets =
  (I "what" Hot HYDRA.Texture :> I "angle" Hot HYDRA.Value :> I "speed" Hot HYDRA.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HYDRA.Texture, angle :: HYDRA.Value, speed :: HYDRA.Value)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "rotate" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "rotate" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "rotate" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HYDRA.Empty, angle: HYDRA.Number 10.0, speed: HYDRA.Number 1.0 }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_angle = Noodle.Inlet :: _ "angle"
_in_speed = Noodle.Inlet :: _ "speed"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _rotate defaultSt (Noodle.Shape :: Shape) defaultI defaultO rotateP

makeNode :: Effect Node
makeNode = Family.spawn family

rotateP :: Process
rotateP = do
  what <- Fn.receive _in_what
  angle <- Fn.receive _in_angle
  speed <- Fn.receive _in_speed
  Fn.send _out_out $ HYDRA.Geometry what $ HYDRA.GRotate { angle, speed }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
