module Test.Files.CodeGenTest.Hydra.Geometry.Rotate where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. -}

_rotate :: NId.Family "rotate"
_rotate = NId.Family

type Inlets =
  (I "what" Hot HT.Texture :> I "angle" Hot HT.Value :> I "speed" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, angle :: HT.Value, speed :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "rotate" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "rotate" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "rotate" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, angle: HT.Number 10.0, speed: HT.Number 1.0 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_angle = Noodle.Inlet :: _ "angle"
_in_speed = Noodle.Inlet :: _ "speed"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _rotate (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO rotateP

makeNode :: Effect Node
makeNode = Family.spawn family

rotateP :: Process
rotateP = do
  what <- Fn.receive _in_what
  angle <- Fn.receive _in_angle
  speed <- Fn.receive _in_speed
  Fn.send _out_out $ HT.Geometry what $ HT.GRotate { angle, speed }
