module Test.Files.CodeGenTest.Hydra.Geometry.Scale where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Noodle.Fn.ToFn (Fn(..))
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: geometry. Family :: scale.

[[ : geometry : scale :: <what:Texture {EMP T} -> amount:Value {N 1.5} -> xMult:Value {N 1.0} -> yMult:Value {N 1.0} -> offsetX:Value {N 0.5} -> offsetY:Value {N 0.5}> => out:Texture {EMP T} /-| out::HT.Geometry <what> $ HT.GScale { <amount>, <xMult>, <yMult>, <offsetX>, <offsetY> } |-/ ]] (#22) -}

_scale :: NId.Family "scale"
_scale = NId.Family

type Inlets =
  ( I "what" Hot HT.Texture :> I "amount" Hot HT.Value :> I "xMult" Hot HT.Value
      :> I "yMult" Hot HT.Value
      :> I "offsetX" Hot HT.Value
      :> I "offsetY" Hot HT.Value
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow =
  ( what :: HT.Texture
  , amount :: HT.Value
  , xMult :: HT.Value
  , yMult :: HT.Value
  , offsetX :: HT.Value
  , offsetY :: HT.Value
  )

type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "scale" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "scale" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "scale" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI =
  { what: HT.Empty
  , amount: HT.Number 1.5
  , xMult: HT.Number 1.0
  , yMult: HT.Number 1.0
  , offsetX: HT.Number 0.5
  , offsetY: HT.Number 0.5
  }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_amount = Noodle.Inlet :: _ "amount"
_in_xMult = Noodle.Inlet :: _ "xMult"
_in_yMult = Noodle.Inlet :: _ "yMult"
_in_offsetX = Noodle.Inlet :: _ "offsetX"
_in_offsetY = Noodle.Inlet :: _ "offsetY"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _scale (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO scaleP

makeNode :: Effect Node
makeNode = Family.spawn family

scaleP :: Process
scaleP = do
  what <- Fn.receive _in_what
  amount <- Fn.receive _in_amount
  xMult <- Fn.receive _in_xMult
  yMult <- Fn.receive _in_yMult
  offsetX <- Fn.receive _in_offsetX
  offsetY <- Fn.receive _in_offsetY
  Fn.send _out_out $ HT.Geometry what $ HT.GScale { amount, xMult, yMult, offsetX, offsetY }
