module INPUT.Test.Files.CodeGenTest.Hydra.Geometry.Scale where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HYDRAW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: geometry. Family :: scale.

[[ : geometry : scale :: <what:Texture {EMP T} -> amount:Value {N 1.5} -> xMult:Value {N 1.0} -> yMult:Value {N 1.0} -> offsetX:Value {N 0.5} -> offsetY:Value {N 0.5}> => out:Texture {EMP T} /-| out::HYDRA.Geometry <what> $ HYDRA.GScale { <amount>, <xMult>, <yMult>, <offsetX>, <offsetY> } |-/ ]] (#22) -}

_scale :: NId.Family "scale"
_scale = NId.Family

type Inlets =
  ( I "what" Hot HYDRA.Texture :> I "amount" Hot HYDRA.Value :> I "xMult" Hot HYDRA.Value
      :> I "yMult" Hot HYDRA.Value
      :> I "offsetX" Hot HYDRA.Value
      :> I "offsetY" Hot HYDRA.Value
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow =
  ( what :: HYDRA.Texture
  , amount :: HYDRA.Value
  , xMult :: HYDRA.Value
  , yMult :: HYDRA.Value
  , offsetX :: HYDRA.Value
  , offsetY :: HYDRA.Value
  )

type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "scale" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "scale" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "scale" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI =
  { what: HYDRA.Empty
  , amount: HYDRA.Number 1.5
  , xMult: HYDRA.Number 1.0
  , yMult: HYDRA.Number 1.0
  , offsetX: HYDRA.Number 0.5
  , offsetY: HYDRA.Number 0.5
  }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_amount = Noodle.Inlet :: _ "amount"
_in_xMult = Noodle.Inlet :: _ "xMult"
_in_yMult = Noodle.Inlet :: _ "yMult"
_in_offsetX = Noodle.Inlet :: _ "offsetX"
_in_offsetY = Noodle.Inlet :: _ "offsetY"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _scale defaultSt (Noodle.Shape :: Shape) defaultI defaultO scaleP

makeNode :: Effect Node
makeNode = Family.spawn family

scaleP :: Process
scaleP = do
  what <- Fn.receive _in_what
  amount <- Fn.receive _in_amount
  xMult <- Fn.receive _in_xMult
  yMult <- Fn.receive _in_yMult
  offsetX <- Fn.receive _in_offsetX
  offsetY <- Fn.receive _in_offsetY
  Fn.send _out_out $ HYDRA.Geometry what $ HYDRA.GScale { amount, xMult, yMult, offsetX, offsetY }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
