module Test.Files.CodeGenTest.Hydra.Geometry.Scroll where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. Group :: geometry. Family :: scroll.

[[ : geometry : scroll :: <what:Texture {EMP T} -> scrollX:Value {N 0.5} -> scrollY:Value {N 0.5} -> speedX:Value -> speedY:Value> => out:Texture {EMP T} /-| out::HT.Geometry <what> $ HT.GScroll { <scrollX>, <scrollY>, <speedX>, <speedY> } |-/ ]]

Toolkit : Hydra. File: ./src/Hydra/hydra.v0.3.ndf -}

_scroll :: NId.Family "scroll"
_scroll = NId.Family

type Inlets =
  ( I "what" Hot HT.Texture :> I "scrollX" Hot HT.Value :> I "scrollY" Hot HT.Value
      :> I "speedX" Hot HT.Value
      :> I "speedY" Hot HT.Value
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow =
  ( what :: HT.Texture
  , scrollX :: HT.Value
  , scrollY :: HT.Value
  , speedX :: HT.Value
  , speedY :: HT.Value
  )

type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "scroll" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "scroll" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "scroll" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI =
  { what: HT.Empty
  , scrollX: HT.Number 0.5
  , scrollY: HT.Number 0.5
  , speedX: HT.None
  , speedY: HT.None
  }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_scrollX = Noodle.Inlet :: _ "scrollX"
_in_scrollY = Noodle.Inlet :: _ "scrollY"
_in_speedX = Noodle.Inlet :: _ "speedX"
_in_speedY = Noodle.Inlet :: _ "speedY"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _scroll (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO scrollP

makeNode :: Effect Node
makeNode = Family.spawn family

scrollP :: Process
scrollP = do
  what <- Fn.receive _in_what
  scrollX <- Fn.receive _in_scrollX
  scrollY <- Fn.receive _in_scrollY
  speedX <- Fn.receive _in_speedX
  speedY <- Fn.receive _in_speedY
  Fn.send _out_out $ HT.Geometry what $ HT.GScroll { scrollX, scrollY, speedX, speedY }
