module Test.Files.CodeGenTest.Hydra.Geometry.ScrollY where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Noodle.Fn.ToFn (Fn(..))
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: geometry. Family :: scrollY.

[[ : geometry : scrollY :: <what:Texture {EMP T} -> scrollY:Value {N 0.5} -> speed:Value {N 1.0}> => out:Texture {EMP T} /-| out::HT.Geometry <what> $ HT.GScrollY { <scrollY>, <speed> } |-/ ]] (#30) -}

_scrollY :: NId.Family "scrollY"
_scrollY = NId.Family

type Inlets =
  (I "what" Hot HT.Texture :> I "scrollY" Hot HT.Value :> I "speed" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, scrollY :: HT.Value, speed :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "scrollY" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "scrollY" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "scrollY" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, scrollY: HT.Number 0.5, speed: HT.Number 1.0 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_scrollY = Noodle.Inlet :: _ "scrollY"
_in_speed = Noodle.Inlet :: _ "speed"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _scrollY (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO scrollYP

makeNode :: Effect Node
makeNode = Family.spawn family

scrollYP :: Process
scrollYP = do
  what <- Fn.receive _in_what
  scrollY <- Fn.receive _in_scrollY
  speed <- Fn.receive _in_speed
  Fn.send _out_out $ HT.Geometry what $ HT.GScrollY { scrollY, speed }
