module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Geometry.ScrollY where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: geometry. Family :: scrollY.

[[ : geometry : scrollY :: <what:Texture {EMP T} -> scrollY:Value {N 0.5} -> speed:Value {N 1.0}> => out:Texture {EMP T} /-| out::HYDRA.Geometry <what> $ HYDRA.GScrollY { <scrollY>, <speed> } |-/ ]] (#30) -}

_scrollY :: NId.Family "scrollY"
_scrollY = NId.Family

type Inlets =
  (I "what" Hot HYDRA.Texture :> I "scrollY" Hot HYDRA.Value :> I "speed" Hot HYDRA.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HYDRA.Texture, scrollY :: HYDRA.Value, speed :: HYDRA.Value)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "scrollY" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "scrollY" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "scrollY" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HYDRA.Empty, scrollY: HYDRA.Number 0.5, speed: HYDRA.Number 1.0 }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_scrollY = Noodle.Inlet :: _ "scrollY"
_in_speed = Noodle.Inlet :: _ "speed"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _scrollY defaultSt (Noodle.Shape :: Shape) defaultI defaultO scrollYP

makeNode :: Effect Node
makeNode = Family.spawn family

scrollYP :: Process
scrollYP = do
  what <- Fn.receive _in_what
  scrollY <- Fn.receive _in_scrollY
  speed <- Fn.receive _in_speed
  Fn.send _out_out $ HYDRA.Geometry what $ HYDRA.GScrollY { scrollY, speed }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
