module StarterTk.Simple.Gennum where

import Prelude

import Demo.Toolkit.Starter.Repr (StarterRepr)
import Effect (Effect)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Data.Tuple.Nested ((/\), type (/\))
import Demo.Toolkit.Starter.Repr as PR

{- Generated by Noodle Codegen from NDF file. Group :: simple. Family :: gennum.

[[  simple : gennum :: <> => out:Number {#/0.0} ]] (#4) -}

_gennum :: NId.Family "gennum"
_gennum = NId.Family

type Inlets = TNil :: Noodle.Inlets
type Outlets = (O "out" Number :> TNil) :: Noodle.Outlets
type InletsRow = ()
type OutletsRow = (out :: Number)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process StarterRepr InletsRow OutletsRow StarterRepr Effect
type Node = Noodle.Node "gennum" StarterRepr InletsRow OutletsRow StarterRepr Effect
type Family = Noodle.Family "gennum" StarterRepr InletsRow OutletsRow StarterRepr Effect
type F = Noodle.F "gennum" StarterRepr InletsRow OutletsRow StarterRepr Effect

defaultI :: Record InletsRow
defaultI = {}

defaultO :: Record OutletsRow
defaultO = { out: 0.0 }

_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _gennum PR.VNone (Noodle.Shape :: Shape) defaultI defaultO gennumP

makeNode :: Effect Node
makeNode = Family.spawn family

gennumP :: Process
gennumP = pure unit
