module Test.Files.CodeGenTest.Input.Hydra.Color.A where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: color. Family :: a.

[[ : color : a :: <what:Texture {EMP T} -> scale:Value {N 1.0} -> offset:Value {N 0.0}> => out:Texture {EMP T} /-| out::HT.Filter <what> $ HT.A { <scale>, <offset> } |-/ ]] (#46) -}

_a :: NId.Family "a"
_a = NId.Family

type Inlets =
  (I "what" Hot HT.Texture :> I "scale" Hot HT.Value :> I "offset" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, scale :: HT.Value, offset :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State HW.WrapRepr
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "a" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "a" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "a" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, scale: HT.Number 1.0, offset: HT.Number 0.0 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

defaultSt :: State
defaultSt = State (HW.Value HT.None)

_in_what = Noodle.Inlet :: _ "what"
_in_scale = Noodle.Inlet :: _ "scale"
_in_offset = Noodle.Inlet :: _ "offset"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _a defaultSt (Noodle.Shape :: Shape) defaultI defaultO aP

makeNode :: Effect Node
makeNode = Family.spawn family

aP :: Process
aP = do
  what <- Fn.receive _in_what
  scale <- Fn.receive _in_scale
  offset <- Fn.receive _in_offset
  Fn.send _out_out $ HT.Filter what $ HT.A { scale, offset }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
