module Test.Files.CodeGenTest.Hydra.Color.Brightness where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. -}

_brightness :: NId.Family "brightness"
_brightness = NId.Family

type Inlets = (I "what" Hot HT.Texture :> I "amount" Hot HT.Value :> TNil) :: Noodle.Inlets
type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, amount :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "brightness" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "brightness" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "brightness" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, amount: HT.Number 0.4 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_amount = Noodle.Inlet :: _ "amount"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _brightness (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO
  brightnessP

makeNode :: Effect Node
makeNode = Family.spawn family

brightnessP :: Process
brightnessP = do
  what <- Fn.receive _in_what
  amount <- Fn.receive _in_amount
  Fn.send _out_out $ HT.Filter what $ HT.Brightness amount
