module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Color.Posterize where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HT
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: color. Family :: posterize.

[[ : color : posterize :: <what:Texture {EMP T} -> bins:Value {N 3.0} -> gamma:Value {N 0.6}> => out:Texture {EMP T} /-| out::HT.Filter <what> $ HT.Posterize { <bins>, <gamma> } |-/ ]] (#31) -}

_posterize :: NId.Family "posterize"
_posterize = NId.Family

type Inlets =
  (I "what" Hot HT.Texture :> I "bins" Hot HT.Value :> I "gamma" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, bins :: HT.Value, gamma :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "posterize" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "posterize" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "posterize" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, bins: HT.Number 3.0, gamma: HT.Number 0.6 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_bins = Noodle.Inlet :: _ "bins"
_in_gamma = Noodle.Inlet :: _ "gamma"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _posterize defaultSt (Noodle.Shape :: Shape) defaultI defaultO posterizeP

makeNode :: Effect Node
makeNode = Family.spawn family

posterizeP :: Process
posterizeP = do
  what <- Fn.receive _in_what
  bins <- Fn.receive _in_bins
  gamma <- Fn.receive _in_gamma
  Fn.send _out_out $ HT.Filter what $ HT.Posterize { bins, gamma }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
