module Test.Files.CodeGenTest.Input.Hydra.Color.Shift where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: color. Family :: shift.

[[ : color : shift :: <what:Texture {EMP T} -> r:Value {N 0.5} -> g:Value {N 0.5} -> b:Value {N 0.5} -> a:Value {N 0.5}> => out:Texture {EMP T} /-| out::HT.Filter <what> $ HT.Shift { <r>, <g>, <b>, <a> } |-/ ]] (#32) -}

_shift :: NId.Family "shift"
_shift = NId.Family

type Inlets =
  ( I "what" Hot HT.Texture :> I "r" Hot HT.Value :> I "g" Hot HT.Value :> I "b" Hot HT.Value
      :> I "a" Hot HT.Value
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, r :: HT.Value, g :: HT.Value, b :: HT.Value, a :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "shift" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "shift" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "shift" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI =
  { what: HT.Empty, r: HT.Number 0.5, g: HT.Number 0.5, b: HT.Number 0.5, a: HT.Number 0.5 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_r = Noodle.Inlet :: _ "r"
_in_g = Noodle.Inlet :: _ "g"
_in_b = Noodle.Inlet :: _ "b"
_in_a = Noodle.Inlet :: _ "a"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _shift defaultSt (Noodle.Shape :: Shape) defaultI defaultO shiftP

makeNode :: Effect Node
makeNode = Family.spawn family

shiftP :: Process
shiftP = do
  what <- Fn.receive _in_what
  r <- Fn.receive _in_r
  g <- Fn.receive _in_g
  b <- Fn.receive _in_b
  a <- Fn.receive _in_a
  Fn.send _out_out $ HT.Filter what $ HT.Shift { r, g, b, a }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
