module Test.Files.CodeGenTest.Hydra.Modulate.ModulateRepeat where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. Group :: modulate. Family :: modulateRepeat.

[[ : modulate : modulateRepeat :: <what:Texture {EMP T} -> with:Texture {EMP T} -> repeatX:Value {N 3.0} -> repeatY:Value {N 3.0} -> offsetX:Value {N 0.5} -> offsetY:Value {N 0.5}> => out:Texture {EMP T} /-| out::HT.ModulateWith { <what>, <with> } $ HT.ModRepeat { <repeatX>, <repeatY>, <offsetX>, <offsetY> } |-/ ]]

Toolkit : Hydra. File: ./src/Hydra/hydra.v0.3.ndf -}

_modulateRepeat :: NId.Family "modulateRepeat"
_modulateRepeat = NId.Family

type Inlets =
  ( I "what" Hot HT.Texture :> I "with" Hot HT.Texture :> I "repeatX" Hot HT.Value
      :> I "repeatY" Hot HT.Value
      :> I "offsetX" Hot HT.Value
      :> I "offsetY" Hot HT.Value
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow =
  ( what :: HT.Texture
  , with :: HT.Texture
  , repeatX :: HT.Value
  , repeatY :: HT.Value
  , offsetX :: HT.Value
  , offsetY :: HT.Value
  )

type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "modulateRepeat" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "modulateRepeat" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "modulateRepeat" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI =
  { what: HT.Empty
  , with: HT.Empty
  , repeatX: HT.Number 3.0
  , repeatY: HT.Number 3.0
  , offsetX: HT.Number 0.5
  , offsetY: HT.Number 0.5
  }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_with = Noodle.Inlet :: _ "with"
_in_repeatX = Noodle.Inlet :: _ "repeatX"
_in_repeatY = Noodle.Inlet :: _ "repeatY"
_in_offsetX = Noodle.Inlet :: _ "offsetX"
_in_offsetY = Noodle.Inlet :: _ "offsetY"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _modulateRepeat (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO
  modulateRepeatP

makeNode :: Effect Node
makeNode = Family.spawn family

modulateRepeatP :: Process
modulateRepeatP = do
  what <- Fn.receive _in_what
  with <- Fn.receive _in_with
  repeatX <- Fn.receive _in_repeatX
  repeatY <- Fn.receive _in_repeatY
  offsetX <- Fn.receive _in_offsetX
  offsetY <- Fn.receive _in_offsetY
  Fn.send _out_out $ HT.ModulateWith { what, with } $ HT.ModRepeat { repeatX, repeatY, offsetX, offsetY }
