module INPUT.Test.Files.CodeGenTest.Hydra.Modulate.ModulateRepeat where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HYDRAW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: modulate. Family :: modulateRepeat.

[[ : modulate : modulateRepeat :: <what:Texture {EMP T} -> with:Texture {EMP T} -> repeatX:Value {N 3.0} -> repeatY:Value {N 3.0} -> offsetX:Value {N 0.5} -> offsetY:Value {N 0.5}> => out:Texture {EMP T} /-| out::HYDRA.ModulateWith { <what>, <with> } $ HYDRA.ModRepeat { <repeatX>, <repeatY>, <offsetX>, <offsetY> } |-/ ]] (#54) -}

_modulateRepeat :: NId.Family "modulateRepeat"
_modulateRepeat = NId.Family

type Inlets =
  ( I "what" Hot HYDRA.Texture :> I "with" Hot HYDRA.Texture :> I "repeatX" Hot HYDRA.Value
      :> I "repeatY" Hot HYDRA.Value
      :> I "offsetX" Hot HYDRA.Value
      :> I "offsetY" Hot HYDRA.Value
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow =
  ( what :: HYDRA.Texture
  , with :: HYDRA.Texture
  , repeatX :: HYDRA.Value
  , repeatY :: HYDRA.Value
  , offsetX :: HYDRA.Value
  , offsetY :: HYDRA.Value
  )

type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "modulateRepeat" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "modulateRepeat" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "modulateRepeat" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI =
  { what: HYDRA.Empty
  , with: HYDRA.Empty
  , repeatX: HYDRA.Number 3.0
  , repeatY: HYDRA.Number 3.0
  , offsetX: HYDRA.Number 0.5
  , offsetY: HYDRA.Number 0.5
  }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_with = Noodle.Inlet :: _ "with"
_in_repeatX = Noodle.Inlet :: _ "repeatX"
_in_repeatY = Noodle.Inlet :: _ "repeatY"
_in_offsetX = Noodle.Inlet :: _ "offsetX"
_in_offsetY = Noodle.Inlet :: _ "offsetY"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _modulateRepeat defaultSt (Noodle.Shape :: Shape) defaultI defaultO
  modulateRepeatP

makeNode :: Effect Node
makeNode = Family.spawn family

modulateRepeatP :: Process
modulateRepeatP = do
  what <- Fn.receive _in_what
  with <- Fn.receive _in_with
  repeatX <- Fn.receive _in_repeatX
  repeatY <- Fn.receive _in_repeatY
  offsetX <- Fn.receive _in_offsetX
  offsetY <- Fn.receive _in_offsetY
  Fn.send _out_out $ HYDRA.ModulateWith { what, with } $ HYDRA.ModRepeat { repeatX, repeatY, offsetX, offsetY }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
