module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Modulate.ModulatePixelate where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: modulate. Family :: modulatePixelate.

[[ : modulate : modulatePixelate :: <what:Texture {EMP T} -> with:Texture {EMP T} -> multiple:Value {N 10.0} -> offset:Value {N 3.0}> => out:Texture {EMP T} /-| out::HYDRA.ModulateWith { <what>, <with> } $ HYDRA.ModPixelate { <multiple>, <offset> } |-/ ]] (#62) -}

_modulatePixelate :: NId.Family "modulatePixelate"
_modulatePixelate = NId.Family

type Inlets =
  ( I "what" Hot HYDRA.Texture :> I "with" Hot HYDRA.Texture :> I "multiple" Hot HYDRA.Value
      :> I "offset" Hot HYDRA.Value
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HYDRA.Texture, with :: HYDRA.Texture, multiple :: HYDRA.Value, offset :: HYDRA.Value)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "modulatePixelate" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "modulatePixelate" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "modulatePixelate" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HYDRA.Empty, with: HYDRA.Empty, multiple: HYDRA.Number 10.0, offset: HYDRA.Number 3.0 }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_with = Noodle.Inlet :: _ "with"
_in_multiple = Noodle.Inlet :: _ "multiple"
_in_offset = Noodle.Inlet :: _ "offset"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _modulatePixelate defaultSt (Noodle.Shape :: Shape) defaultI defaultO
  modulatePixelateP

makeNode :: Effect Node
makeNode = Family.spawn family

modulatePixelateP :: Process
modulatePixelateP = do
  what <- Fn.receive _in_what
  with <- Fn.receive _in_with
  multiple <- Fn.receive _in_multiple
  offset <- Fn.receive _in_offset
  Fn.send _out_out $ HYDRA.ModulateWith { what, with } $ HYDRA.ModPixelate { multiple, offset }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
