module Test.Files.CodeGenTest.Input.Hydra.Modulate.ModulatePixelate where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: modulate. Family :: modulatePixelate.

[[ : modulate : modulatePixelate :: <what:Texture {EMP T} -> with:Texture {EMP T} -> multiple:Value {N 10.0} -> offset:Value {N 3.0}> => out:Texture {EMP T} /-| out::HT.ModulateWith { <what>, <with> } $ HT.ModPixelate { <multiple>, <offset> } |-/ ]] (#62) -}

_modulatePixelate :: NId.Family "modulatePixelate"
_modulatePixelate = NId.Family

type Inlets =
  ( I "what" Hot HT.Texture :> I "with" Hot HT.Texture :> I "multiple" Hot HT.Value
      :> I "offset" Hot HT.Value
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, with :: HT.Texture, multiple :: HT.Value, offset :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "modulatePixelate" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "modulatePixelate" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "modulatePixelate" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, with: HT.Empty, multiple: HT.Number 10.0, offset: HT.Number 3.0 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

defaultSt :: HW.WrapRepr
defaultSt = HW.Value HT.None

_in_what = Noodle.Inlet :: _ "what"
_in_with = Noodle.Inlet :: _ "with"
_in_multiple = Noodle.Inlet :: _ "multiple"
_in_offset = Noodle.Inlet :: _ "offset"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _modulatePixelate defaultSt (Noodle.Shape :: Shape) defaultI defaultO
  modulatePixelateP

makeNode :: Effect Node
makeNode = Family.spawn family

modulatePixelateP :: Process
modulatePixelateP = do
  what <- Fn.receive _in_what
  with <- Fn.receive _in_with
  multiple <- Fn.receive _in_multiple
  offset <- Fn.receive _in_offset
  Fn.send _out_out $ HT.ModulateWith { what, with } $ HT.ModPixelate { multiple, offset }
