module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Modulate.Modulate where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HT
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: modulate. Family :: modulate.

[[ : modulate : modulate :: <what:Texture {EMP T} -> with:Texture {EMP T} -> amount:Value {N 0.1}> => out:Texture {EMP T} /-| out::HT.ModulateWith { <what>, <with> } $ HT.Modulate <amount> |-/ ]] (#60) -}

_modulate :: NId.Family "modulate"
_modulate = NId.Family

type Inlets =
  (I "what" Hot HT.Texture :> I "with" Hot HT.Texture :> I "amount" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, with :: HT.Texture, amount :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "modulate" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "modulate" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "modulate" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, with: HT.Empty, amount: HT.Number 0.1 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_with = Noodle.Inlet :: _ "with"
_in_amount = Noodle.Inlet :: _ "amount"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _modulate defaultSt (Noodle.Shape :: Shape) defaultI defaultO modulateP

makeNode :: Effect Node
makeNode = Family.spawn family

modulateP :: Process
modulateP = do
  what <- Fn.receive _in_what
  with <- Fn.receive _in_with
  amount <- Fn.receive _in_amount
  Fn.send _out_out $ HT.ModulateWith { what, with } $ HT.Modulate amount

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
