module Test.Files.CodeGenTest.Hydra.Modulate.ModulateScrollY where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. -}

_modulateScrollY :: NId.Family "modulateScrollY"
_modulateScrollY = NId.Family

type Inlets =
  ( I "what" Hot HT.Texture :> I "with" Hot HT.Texture :> I "scrollY" Hot HT.Value
      :> I "speed" Hot HT.Value
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, with :: HT.Texture, scrollY :: HT.Value, speed :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "modulateScrollY" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "modulateScrollY" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "modulateScrollY" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, with: HT.Empty, scrollY: HT.Number 0.5, speed: HT.None }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_with = Noodle.Inlet :: _ "with"
_in_scrollY = Noodle.Inlet :: _ "scrollY"
_in_speed = Noodle.Inlet :: _ "speed"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _modulateScrollY (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO
  modulateScrollYP

makeNode :: Effect Node
makeNode = Family.spawn family

modulateScrollYP :: Process
modulateScrollYP = do
  what <- Fn.receive _in_what
  with <- Fn.receive _in_with
  scrollY <- Fn.receive _in_scrollY
  speed <- Fn.receive _in_speed
  Fn.send _out_out $ HT.ModulateWith { what, with } $ HT.ModScrollY { scrollY, speed }
