module Noodle.Text.NdfFile.UnitRepr where

import Prelude


import Data.Maybe (Maybe(..))

import Type.Proxy (Proxy(..))

import Partial.Unsafe (unsafePartial)

import Tidy.Codegen (exprCtor, typeCtor, declImport)

import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Repr.ValueInChannel (class FromValueInChannel, class ToValueInChannel)
import Noodle.Repr.ValueInChannel (accept) as ViC
import Noodle.Fn.Shape.Temperament (defaultAlgorithm) as Temperament
import Noodle.Text.NdfFile.FamilyDef.Codegen (class CodegenRepr, Options(..), groupPascalCase, familyPascalCase)
import Noodle.Text.NdfFile.Codegen (toolkitModuleName) as CG


data UnitRepr = UnitRepr


instance CodegenRepr UnitRepr where
    reprModule = const "Noodle.Text.NdfFile.UnitRepr"
    reprTypeName = const "UnitRepr"
    reprType = const $ unsafePartial $ typeCtor "UnitRepr"
    pTypeFor = const $ unsafePartial $ const $ typeCtor "UnitRepr"
    pDefaultFor = const $ unsafePartial $ const $ exprCtor "UnitRepr"
    pValueFor = const $ const $ const $ unsafePartial $ exprCtor "UnitRepr"
    fTypeFor = const $ unsafePartial $ const $ typeCtor "UnitRepr"
    fDefaultFor = const $ unsafePartial $ const $ exprCtor "UnitRepr"
    fValueFor = const $ const $ const $ unsafePartial $ exprCtor "UnitRepr"


options :: Options UnitRepr UnitRepr
options = Options $
    { streprAt : { module_ : "Noodle.Text.NdfFile.UnitRepr", type_ : "UnitRepr" }
    , chreprAt : { module_ : "Noodle.Text.NdfFile.UnitRepr", type_ : "UnitRepr" }
    , temperamentAlgorithm : Temperament.defaultAlgorithm
    , monadAt : { module_ : "Effect", type_ : "Effect" }
    , familyModuleName : \fgroup family -> "MyToolkit" <> "." <> groupPascalCase fgroup <> "." <> familyPascalCase family
    , toolkitModuleName : CG.toolkitModuleName
    , pstrepr : (Proxy :: _ UnitRepr)
    , pchrepr : (Proxy :: _ UnitRepr)
    , infoComment : Just $ \mbSource fgroup family ->
            "Generated by Noodle Codegen from NDF file. Group :: " <> show fgroup <> ". Family :: " <> show family <> "." <> case mbSource of
            Just src -> "\n\n[[ " <> src.line <> " ]] (#" <> show src.lineIndex <> ")"
            Nothing -> ""
    , tkImports : genericImports
    , familyImports : const genericImports
    }
    where
        genericImports = unsafePartial $
            [ declImport "Noodle.Text.NdfFile.UnitRepr" []
            ]


instance HasFallback UnitRepr where
    fallback = UnitRepr


instance FromValueInChannel UnitRepr UnitRepr
    where fromValueInChannel = identity


instance ToValueInChannel UnitRepr UnitRepr
    where toValueInChannel = ViC.accept