module Test.Files.CodeGenTest.Input.Hydra.Source.Noise where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HT
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: source. Family :: noise.

[[  source : noise :: <scale:Value {N 10.0} -> offset:Value {N 0.1}> => out:Texture {EMP T} /-| out::HT.Start $ HT.From $ HT.Noise { <scale>, <offset> } |-/ ]] (#14) -}

_noise :: NId.Family "noise"
_noise = NId.Family

type Inlets = (I "scale" Hot HT.Value :> I "offset" Hot HT.Value :> TNil) :: Noodle.Inlets
type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (scale :: HT.Value, offset :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "noise" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "noise" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "noise" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { scale: HT.Number 10.0, offset: HT.Number 0.1 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

defaultSt :: State
defaultSt = State unit

_in_scale = Noodle.Inlet :: _ "scale"
_in_offset = Noodle.Inlet :: _ "offset"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _noise defaultSt (Noodle.Shape :: Shape) defaultI defaultO noiseP

makeNode :: Effect Node
makeNode = Family.spawn family

noiseP :: Process
noiseP = do
  scale <- Fn.receive _in_scale
  offset <- Fn.receive _in_offset
  Fn.send _out_out $ HT.Start $ HT.From $ HT.Noise { scale, offset }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
