module Test.Files.CodeGenTest.Hydra.Source.Osc where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. Group :: source. Family :: osc.

[[ : source : osc :: <frequency:Value {N 60.0} -> sync:Value {N 0.1} -> offset:Value> => out:Texture {EMP T} /-| out::HT.Start $ HT.From $ HT.Osc { <frequency>, <sync>, <offset> } |-/ ]]

Toolkit : Hydra. File: ./src/Hydra/hydra.v0.3.ndf -}

_osc :: NId.Family "osc"
_osc = NId.Family

type Inlets =
  (I "frequency" Hot HT.Value :> I "sync" Hot HT.Value :> I "offset" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (frequency :: HT.Value, sync :: HT.Value, offset :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "osc" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "osc" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "osc" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { frequency: HT.Number 60.0, sync: HT.Number 0.1, offset: HT.None }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_frequency = Noodle.Inlet :: _ "frequency"
_in_sync = Noodle.Inlet :: _ "sync"
_in_offset = Noodle.Inlet :: _ "offset"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _osc (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO oscP

makeNode :: Effect Node
makeNode = Family.spawn family

oscP :: Process
oscP = do
  frequency <- Fn.receive _in_frequency
  sync <- Fn.receive _in_sync
  offset <- Fn.receive _in_offset
  Fn.send _out_out $ HT.Start $ HT.From $ HT.Osc { frequency, sync, offset }
