module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Source.Osc where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: source. Family :: osc.

[[ : source : osc :: <frequency:Value {N 60.0} -> sync:Value {N 0.1} -> offset:Value> => out:Texture {EMP T} /-| out::HYDRA.Start $ HYDRA.From $ HYDRA.Osc { <frequency>, <sync>, <offset> } |-/ ]] (#15) -}

_osc :: NId.Family "osc"
_osc = NId.Family

type Inlets =
  (I "frequency" Hot HYDRA.Value :> I "sync" Hot HYDRA.Value :> I "offset" Hot HYDRA.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (frequency :: HYDRA.Value, sync :: HYDRA.Value, offset :: HYDRA.Value)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "osc" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "osc" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "osc" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { frequency: HYDRA.Number 60.0, sync: HYDRA.Number 0.1, offset: HYDRA.None }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_frequency = Noodle.Inlet :: _ "frequency"
_in_sync = Noodle.Inlet :: _ "sync"
_in_offset = Noodle.Inlet :: _ "offset"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _osc defaultSt (Noodle.Shape :: Shape) defaultI defaultO oscP

makeNode :: Effect Node
makeNode = Family.spawn family

oscP :: Process
oscP = do
  frequency <- Fn.receive _in_frequency
  sync <- Fn.receive _in_sync
  offset <- Fn.receive _in_offset
  Fn.send _out_out $ HYDRA.Start $ HYDRA.From $ HYDRA.Osc { frequency, sync, offset }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
