module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Source.Prev where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: source. Family :: prev.

[[ : source : prev :: <todo:TODO {TODO}> => out:Texture {EMP T} /-| out::HYDRA.Empty |-/ ]] (#20) -}

_prev :: NId.Family "prev"
_prev = NId.Family

type Inlets = (I "todo" Hot HYDRA.TODO :> TNil) :: Noodle.Inlets
type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (todo :: HYDRA.TODO)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "prev" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "prev" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "prev" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { todo: HYDRA.TODO }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_todo = Noodle.Inlet :: _ "todo"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _prev defaultSt (Noodle.Shape :: Shape) defaultI defaultO prevP

makeNode :: Effect Node
makeNode = Family.spawn family

prevP :: Process
prevP = do
  Fn.send _out_out $ HYDRA.Empty

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
