module Test.Files.CodeGenTest.Hydra.Source.Shape where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. Group :: source. Family :: shape.

[[ : source : shape :: <sides:Value {N 60.0} -> radius:Value {N 0.3} -> smoothing:Value {N 0.01}> => out:Texture {EMP T} /-| out::HT.Start $ HT.From $ HT.Shape { <sides>, <radius>, <smoothing> } |-/ ]]

Toolkit : Hydra. File: ./src/Hydra/hydra.v0.3.ndf -}

_shape :: NId.Family "shape"
_shape = NId.Family

type Inlets =
  (I "sides" Hot HT.Value :> I "radius" Hot HT.Value :> I "smoothing" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (sides :: HT.Value, radius :: HT.Value, smoothing :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "shape" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "shape" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "shape" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { sides: HT.Number 60.0, radius: HT.Number 0.3, smoothing: HT.Number 0.01 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_sides = Noodle.Inlet :: _ "sides"
_in_radius = Noodle.Inlet :: _ "radius"
_in_smoothing = Noodle.Inlet :: _ "smoothing"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _shape (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO shapeP

makeNode :: Effect Node
makeNode = Family.spawn family

shapeP :: Process
shapeP = do
  sides <- Fn.receive _in_sides
  radius <- Fn.receive _in_radius
  smoothing <- Fn.receive _in_smoothing
  Fn.send _out_out $ HT.Start $ HT.From $ HT.Shape { sides, radius, smoothing }
