module INPUT.Test.Files.CodeGenTest.Hydra.Source.Solid where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: source. Family :: solid.

[[ : source : solid :: <r:Value -> g:Value -> b:Value -> a:Value {N 1.0}> => out:Texture {EMP T} /-| out::HYDRA.Start $ HYDRA.From $ HYDRA.Solid { <r>, <g>, <b>, <a> } |-/ ]] (#18) -}

_solid :: NId.Family "solid"
_solid = NId.Family

type Inlets =
  (I "r" Hot HYDRA.Value :> I "g" Hot HYDRA.Value :> I "b" Hot HYDRA.Value :> I "a" Hot HYDRA.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (r :: HYDRA.Value, g :: HYDRA.Value, b :: HYDRA.Value, a :: HYDRA.Value)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "solid" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "solid" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "solid" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { r: HYDRA.None, g: HYDRA.None, b: HYDRA.None, a: HYDRA.Number 1.0 }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_r = Noodle.Inlet :: _ "r"
_in_g = Noodle.Inlet :: _ "g"
_in_b = Noodle.Inlet :: _ "b"
_in_a = Noodle.Inlet :: _ "a"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _solid defaultSt (Noodle.Shape :: Shape) defaultI defaultO solidP

makeNode :: Effect Node
makeNode = Family.spawn family

solidP :: Process
solidP = do
  r <- Fn.receive _in_r
  g <- Fn.receive _in_g
  b <- Fn.receive _in_b
  a <- Fn.receive _in_a
  Fn.send _out_out $ HYDRA.Start $ HYDRA.From $ HYDRA.Solid { r, g, b, a }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
