module INPUT.Test.Files.CodeGenTest.Hydra.Source.Src where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: source. Family :: src.

[[ : source : src :: <load:OutputN> => out:Texture {EMP T} /-| out::HYDRA.Start $ HYDRA.Load <load> |-/ ]] (#19) -}

_src :: NId.Family "src"
_src = NId.Family

type Inlets = (I "load" Hot HYDRA.OutputN :> TNil) :: Noodle.Inlets
type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (load :: HYDRA.OutputN)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "src" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "src" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "src" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { load: HYDRA.Output0 }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_load = Noodle.Inlet :: _ "load"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _src defaultSt (Noodle.Shape :: Shape) defaultI defaultO srcP

makeNode :: Effect Node
makeNode = Family.spawn family

srcP :: Process
srcP = do
  load <- Fn.receive _in_load
  Fn.send _out_out $ HYDRA.Start $ HYDRA.Load load

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
