module Test.Files.CodeGenTest.Hydra.Source.Src where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. -}

_src :: NId.Family "src"
_src = NId.Family

type Inlets = (I "src" Hot HT.Source :> TNil) :: Noodle.Inlets
type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (src :: HT.Source)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "src" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "src" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "src" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { src: HT.Load HT.Output0 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_src = Noodle.Inlet :: _ "src"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _src (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO srcP

makeNode :: Effect Node
makeNode = Family.spawn family

srcP :: Process
srcP = do
  src <- Fn.receive _in_src
  Fn.send _out_out $ HT.Start $ HT.Source src
