module Test.Files.CodeGenTest.Hydra.Source.Voronoi where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Noodle.Fn.ToFn (Fn(..))
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: source. Family :: voronoi.

[[ : source : voronoi :: <scale:Value {N 5.0} -> speed:Value {N 0.3} -> blending:Value {N 0.3}> => out:Texture {EMP T} /-| out::HT.Start $ HT.From $ HT.Voronoi { <scale>, <speed>, <blending> } |-/ ]] (#14) -}

_voronoi :: NId.Family "voronoi"
_voronoi = NId.Family

type Inlets =
  (I "scale" Hot HT.Value :> I "speed" Hot HT.Value :> I "blending" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (scale :: HT.Value, speed :: HT.Value, blending :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "voronoi" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "voronoi" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "voronoi" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { scale: HT.Number 5.0, speed: HT.Number 0.3, blending: HT.Number 0.3 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_scale = Noodle.Inlet :: _ "scale"
_in_speed = Noodle.Inlet :: _ "speed"
_in_blending = Noodle.Inlet :: _ "blending"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _voronoi (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO voronoiP

makeNode :: Effect Node
makeNode = Family.spawn family

voronoiP :: Process
voronoiP = do
  scale <- Fn.receive _in_scale
  speed <- Fn.receive _in_speed
  blending <- Fn.receive _in_blending
  Fn.send _out_out $ HT.Start $ HT.From $ HT.Voronoi { scale, speed, blending }
