module INPUT.Test.Files.CodeGenTest.Hydra.Source.Voronoi where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: source. Family :: voronoi.

[[ : source : voronoi :: <scale:Value {N 5.0} -> speed:Value {N 0.3} -> blending:Value {N 0.3}> => out:Texture {EMP T} /-| out::HYDRA.Start $ HYDRA.From $ HYDRA.Voronoi { <scale>, <speed>, <blending> } |-/ ]] (#14) -}

_voronoi :: NId.Family "voronoi"
_voronoi = NId.Family

type Inlets =
  (I "scale" Hot HYDRA.Value :> I "speed" Hot HYDRA.Value :> I "blending" Hot HYDRA.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (scale :: HYDRA.Value, speed :: HYDRA.Value, blending :: HYDRA.Value)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "voronoi" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "voronoi" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "voronoi" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { scale: HYDRA.Number 5.0, speed: HYDRA.Number 0.3, blending: HYDRA.Number 0.3 }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_scale = Noodle.Inlet :: _ "scale"
_in_speed = Noodle.Inlet :: _ "speed"
_in_blending = Noodle.Inlet :: _ "blending"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _voronoi defaultSt (Noodle.Shape :: Shape) defaultI defaultO voronoiP

makeNode :: Effect Node
makeNode = Family.spawn family

voronoiP :: Process
voronoiP = do
  scale <- Fn.receive _in_scale
  speed <- Fn.receive _in_speed
  blending <- Fn.receive _in_blending
  Fn.send _out_out $ HYDRA.Start $ HYDRA.From $ HYDRA.Voronoi { scale, speed, blending }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
