module Test.Files.CodeGenTest.Hydra.Blend.Blend where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Noodle.Fn.ToFn (Fn(..))
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: blend. Family :: blend.

[[ : blend : blend :: <what:Texture {EMP T} -> with:Texture {EMP T} -> amount:Value {N 0.5}> => out:Texture {EMP T} /-| out::HT.BlendOf { <what>, <with> } $ HT.Blend <amount> |-/ ]]

Toolkit : Hydra. File: ./src/Hydra/hydra.v0.3.ndf -}

_blend :: NId.Family "blend"
_blend = NId.Family

type Inlets =
  (I "what" Hot HT.Texture :> I "with" Hot HT.Texture :> I "amount" Hot HT.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, with :: HT.Texture, amount :: HT.Value)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "blend" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "blend" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "blend" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, with: HT.Empty, amount: HT.Number 0.5 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_with = Noodle.Inlet :: _ "with"
_in_amount = Noodle.Inlet :: _ "amount"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _blend (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO blendP

makeNode :: Effect Node
makeNode = Family.spawn family

blendP :: Process
blendP = do
  what <- Fn.receive _in_what
  with <- Fn.receive _in_with
  amount <- Fn.receive _in_amount
  Fn.send _out_out $ HT.BlendOf { what, with } $ HT.Blend amount
