module INPUT.Test.Files.CodeGenTest.Hydra.Blend.Layer where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HYDRAW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: blend. Family :: layer.

[[ : blend : layer :: <what:Texture {EMP T} -> with:Texture {EMP T} -> amount:Value {N 1.0}> => out:Texture {EMP T} /-| out::HYDRA.BlendOf { <what>, <with> } $ HYDRA.Layer <amount> |-/ ]] (#49) -}

_layer :: NId.Family "layer"
_layer = NId.Family

type Inlets =
  (I "what" Hot HYDRA.Texture :> I "with" Hot HYDRA.Texture :> I "amount" Hot HYDRA.Value :> TNil) ::
    Noodle.Inlets

type Outlets = (O "out" HYDRA.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HYDRA.Texture, with :: HYDRA.Texture, amount :: HYDRA.Value)
type OutletsRow = (out :: HYDRA.Texture)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "layer" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "layer" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "layer" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HYDRA.Empty, with: HYDRA.Empty, amount: HYDRA.Number 1.0 }

defaultO :: Record OutletsRow
defaultO = { out: HYDRA.Empty }

defaultSt :: State
defaultSt = State unit

_in_what = Noodle.Inlet :: _ "what"
_in_with = Noodle.Inlet :: _ "with"
_in_amount = Noodle.Inlet :: _ "amount"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _layer defaultSt (Noodle.Shape :: Shape) defaultI defaultO layerP

makeNode :: Effect Node
makeNode = Family.spawn family

layerP :: Process
layerP = do
  what <- Fn.receive _in_what
  with <- Fn.receive _in_with
  amount <- Fn.receive _in_amount
  Fn.send _out_out $ HYDRA.BlendOf { what, with } $ HYDRA.Layer amount

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
