module Test.Files.CodeGenTest.Hydra.Blend.Mask where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. Group :: blend. Family :: mask.

[[ : blend : mask :: <what:Texture {EMP T} -> with:Texture {EMP T}> => out:Texture {EMP T} /-| out::HT.BlendOf { <what>, <with> } $ HT.Mask |-/ ]]

Toolkit : Hydra. File: ./src/Hydra/hydra.v0.3.ndf -}

_mask :: NId.Family "mask"
_mask = NId.Family

type Inlets = (I "what" Hot HT.Texture :> I "with" Hot HT.Texture :> TNil) :: Noodle.Inlets
type Outlets = (O "out" HT.Texture :> TNil) :: Noodle.Outlets
type InletsRow = (what :: HT.Texture, with :: HT.Texture)
type OutletsRow = (out :: HT.Texture)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "mask" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "mask" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "mask" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { what: HT.Empty, with: HT.Empty }

defaultO :: Record OutletsRow
defaultO = { out: HT.Empty }

_in_what = Noodle.Inlet :: _ "what"
_in_with = Noodle.Inlet :: _ "with"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _mask (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO maskP

makeNode :: Effect Node
makeNode = Family.spawn family

maskP :: Process
maskP = do
  what <- Fn.receive _in_what
  with <- Fn.receive _in_with
  Fn.send _out_out $ HT.BlendOf { what, with } $ HT.Mask
