module Test.Files.CodeGenTest.Hydra.Feed.Number where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. Group :: feed. Family :: number.

[[ : feed : number :: <in:Value {N 0.0}> => out:Value {N 0.0} ]]

Toolkit : Hydra. File: ./src/Hydra/hydra.v0.3.ndf -}

_number :: NId.Family "number"
_number = NId.Family

type Inlets = (I "in" Hot HT.Value :> TNil) :: Noodle.Inlets
type Outlets = (O "out" HT.Value :> TNil) :: Noodle.Outlets
type InletsRow = (in :: HT.Value)
type OutletsRow = (out :: HT.Value)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "number" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "number" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "number" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { in: HT.Number 0.0 }

defaultO :: Record OutletsRow
defaultO = { out: HT.Number 0.0 }

_in_in = Noodle.Inlet :: _ "in"
_out_out = Noodle.Outlet :: _ "out"

family :: Family
family = Family.make _number (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO numberP

makeNode :: Effect Node
makeNode = Family.spawn family

numberP :: Process
numberP = pure unit
