module Test.Files.CodeGenTest.Input.Hydra.Extsource.InitCam where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: extsource. Family :: initCam.

[[  extsource : initCam :: <src:SourceN -> index:Value {0 V}> => <> ]] (#75) -}

_initCam :: NId.Family "initCam"
_initCam = NId.Family

type Inlets = (I "src" Hot HT.SourceN :> I "index" Hot HT.Value :> TNil) :: Noodle.Inlets
type Outlets = TNil :: Noodle.Outlets
type InletsRow = (src :: HT.SourceN, index :: HT.Value)
type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
newtype State = State HW.WrapRepr
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "initCam" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "initCam" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "initCam" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { src: HT.Source0, index: HT.None }

defaultO :: Record OutletsRow
defaultO = {}

defaultSt :: State
defaultSt = State (HW.Value HT.None)

_in_src = Noodle.Inlet :: _ "src"
_in_index = Noodle.Inlet :: _ "index"

family :: Family
family = Family.make _initCam defaultSt (Noodle.Shape :: Shape) defaultI defaultO initCamP

makeNode :: Effect Node
makeNode = Family.spawn family

initCamP :: Process
initCamP = {- EMPTY PROCESS -}
    pure unit

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
