module StarterTk.Simple.Letter where

import Prelude

import Demo.Toolkit.Starter.Repr (ValueRepr)
import Effect (Effect)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Data.Tuple.Nested ((/\), type (/\))
import Demo.Toolkit.Starter.Repr as VR

{- Generated by Noodle Codegen from NDF file. Group :: simple. Family :: letter.

[[  simple : letter :: <code:Number> => letter:Char ]] (#10) -}

_letter :: NId.Family "letter"
_letter = NId.Family

type Inlets = (I "code" Hot Number :> TNil) :: Noodle.Inlets
type Outlets = (O "letter" Char :> TNil) :: Noodle.Outlets
type InletsRow = (code :: Number)
type OutletsRow = (letter :: Char)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process Unit InletsRow OutletsRow ValueRepr Effect
type Node = Noodle.Node "letter" Unit InletsRow OutletsRow ValueRepr Effect
type Family = Noodle.Family "letter" Unit InletsRow OutletsRow ValueRepr Effect
type F = Noodle.F "letter" Unit InletsRow OutletsRow ValueRepr Effect

defaultI :: Record InletsRow
defaultI = { code: 0.0 }

defaultO :: Record OutletsRow
defaultO = { letter: '-' }

_in_code = Noodle.Inlet :: _ "code"
_out_letter = Noodle.Outlet :: _ "letter"

family :: Family
family = Family.make _letter unit (Noodle.Shape :: Shape) defaultI defaultO letterP

makeNode :: Effect Node
makeNode = Family.spawn family

letterP :: Process
letterP = pure unit
