module StarterTk.Simple.Log where

import Prelude

import Demo.Toolkit.Starter.Repr (ValueRepr)
import Effect (Effect)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Data.Tuple.Nested ((/\), type (/\))
import Demo.Toolkit.Starter.Repr as PR

{- Generated by Noodle Codegen from NDF file. Group :: simple. Family :: log.

[[  simple : log :: <what:Any> => <> ]] (#6) -}

_log :: NId.Family "log"
_log = NId.Family

type Inlets = (I "what" Hot PR.Any :> TNil) :: Noodle.Inlets
type Outlets = TNil :: Noodle.Outlets
type InletsRow = (what :: PR.Any)
type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process ValueRepr InletsRow OutletsRow ValueRepr Effect
type Node = Noodle.Node "log" ValueRepr InletsRow OutletsRow ValueRepr Effect
type Family = Noodle.Family "log" ValueRepr InletsRow OutletsRow ValueRepr Effect
type F = Noodle.F "log" ValueRepr InletsRow OutletsRow ValueRepr Effect

defaultI :: Record InletsRow
defaultI = { what: PR.Any PR.VNone }

defaultO :: Record OutletsRow
defaultO = {}

_in_what = Noodle.Inlet :: _ "what"

family :: Family
family = Family.make _log PR.VNone (Noodle.Shape :: Shape) defaultI defaultO logP

makeNode :: Effect Node
makeNode = Family.spawn family

logP :: Process
logP = pure unit
