module StarterTk.Simple.Log where

import Prelude

import Demo.Toolkit.Starter.Repr.ChRepr (ValueRepr)
import Effect (Effect)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Data.Tuple.Nested ((/\), type (/\))
import Demo.Toolkit.Starter.Repr.ChRepr as VR
import Cli.Components.SidePanel.Console as CC
import Blessed.Internal.BlessedOp (runM) as Blessed

{- Generated by Noodle Codegen from NDF file. Group :: simple. Family :: log.

[[  simple : log :: <what:Any> => <> ]] (#6) -}

_log :: NId.Family "log"
_log = NId.Family

type Inlets = (I "what" Hot VR.Any :> TNil) :: Noodle.Inlets
type Outlets = TNil :: Noodle.Outlets
type InletsRow = (what :: VR.Any)
type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process Unit InletsRow OutletsRow ValueRepr Effect
type Node = Noodle.Node "log" Unit InletsRow OutletsRow ValueRepr Effect
type Family = Noodle.Family "log" Unit InletsRow OutletsRow ValueRepr Effect
type F = Noodle.F "log" Unit InletsRow OutletsRow ValueRepr Effect

defaultI :: Record InletsRow
defaultI = { what: VR.Any VR.VNone }

defaultO :: Record OutletsRow
defaultO = {}

_in_what = Noodle.Inlet :: _ "what"

family :: Family
family = Family.make _log unit (Noodle.Shape :: Shape) defaultI defaultO logP

makeNode :: Effect Node
makeNode = Family.spawn family

logP :: Process
logP = pure unit
