module INPUT.Test.Files.CodeGenTest.Hydra.Array.Ease where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HYDRAW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: array. Family :: ease.

[[ : array : ease :: <arr:Values {%%%%} -> ease:Ease {LIN E}> => arr:Value {VA %%%%} /-| arr::HYDRA.VArray <arr> <ease> |-/ ]] (#82) -}

_ease :: NId.Family "ease"
_ease = NId.Family

type Inlets = (I "arr" Hot HYDRA.Values :> I "ease" Hot HYDRA.Ease :> TNil) :: Noodle.Inlets
type Outlets = (O "arr" HYDRA.Value :> TNil) :: Noodle.Outlets
type InletsRow = (arr :: HYDRA.Values, ease :: HYDRA.Ease)
type OutletsRow = (arr :: HYDRA.Value)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "ease" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "ease" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "ease" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { arr: HYDRA.Values [], ease: HYDRA.Ease HYDRA.Linear }

defaultO :: Record OutletsRow
defaultO = { arr: HYDRA.VArray (HYDRA.Values []) HYDRA.NoEase }

defaultSt :: State
defaultSt = State unit

_in_arr = Noodle.Inlet :: _ "arr"
_in_ease = Noodle.Inlet :: _ "ease"
_out_arr = Noodle.Outlet :: _ "arr"

family :: Family
family = Family.make _ease defaultSt (Noodle.Shape :: Shape) defaultI defaultO easeP

makeNode :: Effect Node
makeNode = Family.spawn family

easeP :: Process
easeP = do
  arr <- Fn.receive _in_arr
  ease <- Fn.receive _in_ease
  Fn.send _out_arr $ HYDRA.VArray arr ease

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
