module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Array.Fit where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HT
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: array. Family :: fit.

[[ : array : fit :: <arr:Values {%%%%} -> low:Value {N 0.0} -> high:Value {N 1.0}> => arr:Value {VA %%%%} /-| arr::HT.VArray <arr> $ HT.Fit { <low>, <high> } |-/ ]] (#84) -}

_fit :: NId.Family "fit"
_fit = NId.Family

type Inlets =
  (I "arr" Hot HT.Values :> I "low" Hot HT.Value :> I "high" Hot HT.Value :> TNil) :: Noodle.Inlets

type Outlets = (O "arr" HT.Value :> TNil) :: Noodle.Outlets
type InletsRow = (arr :: HT.Values, low :: HT.Value, high :: HT.Value)
type OutletsRow = (arr :: HT.Value)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "fit" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "fit" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "fit" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { arr: HT.Values [], low: HT.Number 0.0, high: HT.Number 1.0 }

defaultO :: Record OutletsRow
defaultO = { arr: HT.VArray (HT.Values []) (HT.Ease HT.Linear) }

defaultSt :: State
defaultSt = State unit

_in_arr = Noodle.Inlet :: _ "arr"
_in_low = Noodle.Inlet :: _ "low"
_in_high = Noodle.Inlet :: _ "high"
_out_arr = Noodle.Outlet :: _ "arr"

family :: Family
family = Family.make _fit defaultSt (Noodle.Shape :: Shape) defaultI defaultO fitP

makeNode :: Effect Node
makeNode = Family.spawn family

fitP :: Process
fitP = do
  arr <- Fn.receive _in_arr
  low <- Fn.receive _in_low
  high <- Fn.receive _in_high
  Fn.send _out_arr $ HT.VArray arr $ HT.Fit { low, high }

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
