module Test.Files.CodeGenTest.Hydra.Array.Offset where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Noodle.Fn.ToFn (Fn(..))
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: array. Family :: offset.

[[ : array : offset :: <arr:Values {%%%%} -> offset:Value {N 0.5}> => arr:Value {VA %%%%} /-| arr::HT.VArray <arr> $ HT.Offset <offset> |-/ ]]

Toolkit : Hydra. File: ./src/Hydra/hydra.v0.3.ndf -}

_offset :: NId.Family "offset"
_offset = NId.Family

type Inlets = (I "arr" Hot HT.Values :> I "offset" Hot HT.Value :> TNil) :: Noodle.Inlets
type Outlets = (O "arr" HT.Value :> TNil) :: Noodle.Outlets
type InletsRow = (arr :: HT.Values, offset :: HT.Value)
type OutletsRow = (arr :: HT.Value)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "offset" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "offset" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "offset" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { arr: HT.Values [], offset: HT.Number 0.5 }

defaultO :: Record OutletsRow
defaultO = { arr: HT.VArray (HT.Values []) HT.Linear }

_in_arr = Noodle.Inlet :: _ "arr"
_in_offset = Noodle.Inlet :: _ "offset"
_out_arr = Noodle.Outlet :: _ "arr"

family :: Family
family = Family.make _offset (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO offsetP

makeNode :: Effect Node
makeNode = Family.spawn family

offsetP :: Process
offsetP = do
  arr <- Fn.receive _in_arr
  offset <- Fn.receive _in_offset
  Fn.send _out_arr $ HT.VArray arr $ HT.Offset offset
