module INPUT.Test.Files.CodeGenTest.Hydra.Array.Offset where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: array. Family :: offset.

[[ : array : offset :: <arr:Values {%%%%} -> offset:Value {N 0.5}> => arr:Value {VA %%%%} /-| arr::HYDRA.VArray <arr> $ HYDRA.Offset <offset> |-/ ]] (#83) -}

_offset :: NId.Family "offset"
_offset = NId.Family

type Inlets = (I "arr" Hot HYDRA.Values :> I "offset" Hot HYDRA.Value :> TNil) :: Noodle.Inlets
type Outlets = (O "arr" HYDRA.Value :> TNil) :: Noodle.Outlets
type InletsRow = (arr :: HYDRA.Values, offset :: HYDRA.Value)
type OutletsRow = (arr :: HYDRA.Value)
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "offset" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "offset" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "offset" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { arr: HYDRA.Values [], offset: HYDRA.Number 0.5 }

defaultO :: Record OutletsRow
defaultO = { arr: HYDRA.VArray (HYDRA.Values []) (HYDRA.Ease HYDRA.Linear) }

defaultSt :: State
defaultSt = State unit

_in_arr = Noodle.Inlet :: _ "arr"
_in_offset = Noodle.Inlet :: _ "offset"
_out_arr = Noodle.Outlet :: _ "arr"

family :: Family
family = Family.make _offset defaultSt (Noodle.Shape :: Shape) defaultI defaultO offsetP

makeNode :: Effect Node
makeNode = Family.spawn family

offsetP :: Process
offsetP = do
  arr <- Fn.receive _in_arr
  offset <- Fn.receive _in_offset
  Fn.send _out_arr $ HYDRA.VArray arr $ HYDRA.Offset offset

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
