module StarterTk.Spreads.Vspread where

import Prelude

import Demo.Toolkit.Starter.Repr.ChRepr (ValueRepr)
import Effect (Effect)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Data.Tuple.Nested ((/\), type (/\))
import Demo.Toolkit.Starter.Repr.ChRepr as VR

{- Generated by Noodle Codegen from NDF file. Group :: spreads. Family :: vspread.

[[  spreads : vspread :: <x:SpreadN -> y:SpreadN> => spread:SpreadV ]] (#16) -}

_vspread :: NId.Family "vspread"
_vspread = NId.Family

type Inlets =
  (I "x" Hot (VR.Spread Number) :> I "y" Hot (VR.Spread Number) :> TNil) :: Noodle.Inlets

type Outlets = (O "spread" (VR.Spread (Number /\ Number)) :> TNil) :: Noodle.Outlets
type InletsRow = (x :: VR.Spread Number, y :: VR.Spread Number)
type OutletsRow = (spread :: VR.Spread (Number /\ Number))
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process Unit InletsRow OutletsRow ValueRepr Effect
type Node = Noodle.Node "vspread" Unit InletsRow OutletsRow ValueRepr Effect
type Family = Noodle.Family "vspread" Unit InletsRow OutletsRow ValueRepr Effect
type F = Noodle.F "vspread" Unit InletsRow OutletsRow ValueRepr Effect

defaultI :: Record InletsRow
defaultI = { x: VR.Spread [], y: VR.Spread [] }

defaultO :: Record OutletsRow
defaultO = { spread: VR.Spread [] }

_in_x = Noodle.Inlet :: _ "x"
_in_y = Noodle.Inlet :: _ "y"
_out_spread = Noodle.Outlet :: _ "spread"

family :: Family
family = Family.make _vspread unit (Noodle.Shape :: Shape) defaultI defaultO vspreadP

makeNode :: Effect Node
makeNode = Family.spawn family

vspreadP :: Process
vspreadP = pure unit
