module StarterTk.Spreads.Xsshape where

import Prelude

import Demo.Toolkit.Starter.Repr (ValueRepr)
import Effect (Effect)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Data.Tuple.Nested ((/\), type (/\))
import Demo.Toolkit.Starter.Repr as VR

{- Generated by Noodle Codegen from NDF file. Group :: spreads. Family :: xsshape.

[[  spreads : xsshape :: <pos:SpreadN -> color:SpreadC -> size:SpreadV -> angle:SpreadN> => shape:SpreadS ]] (#18) -}

_xsshape :: NId.Family "xsshape"
_xsshape = NId.Family

type Inlets =
  ( I "pos" Hot (VR.Spread Number) :> I "color" Hot (VR.Spread VR.Color)
      :> I "size" Hot (VR.Spread (Number /\ Number))
      :> I "angle" Hot (VR.Spread Number)
      :> TNil
  ) :: Noodle.Inlets

type Outlets = (O "shape" (VR.Spread VR.Shape) :> TNil) :: Noodle.Outlets
type InletsRow =
  ( pos :: VR.Spread Number
  , color :: VR.Spread VR.Color
  , size :: VR.Spread (Number /\ Number)
  , angle :: VR.Spread Number
  )

type OutletsRow = (shape :: VR.Spread VR.Shape)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process Unit InletsRow OutletsRow ValueRepr Effect
type Node = Noodle.Node "xsshape" Unit InletsRow OutletsRow ValueRepr Effect
type Family = Noodle.Family "xsshape" Unit InletsRow OutletsRow ValueRepr Effect
type F = Noodle.F "xsshape" Unit InletsRow OutletsRow ValueRepr Effect

defaultI :: Record InletsRow
defaultI = { pos: VR.Spread [], color: VR.Spread [], size: VR.Spread [], angle: VR.Spread [] }

defaultO :: Record OutletsRow
defaultO = { shape: VR.Spread [] }

_in_pos = Noodle.Inlet :: _ "pos"
_in_color = Noodle.Inlet :: _ "color"
_in_size = Noodle.Inlet :: _ "size"
_in_angle = Noodle.Inlet :: _ "angle"
_out_shape = Noodle.Outlet :: _ "shape"

family :: Family
family = Family.make _xsshape unit (Noodle.Shape :: Shape) defaultI defaultO xsshapeP

makeNode :: Effect Node
makeNode = Family.spawn family

xsshapeP :: Process
xsshapeP = pure unit
