module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Audio.Hide where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: audio. Family :: hide.

[[  audio : hide :: <audio:Audio {SIL} -> todo:TODO {TODO}> => <> ]] (#91) -}

_hide :: NId.Family "hide"
_hide = NId.Family

type Inlets = (I "audio" Hot HYDRA.AudioSource :> I "todo" Hot HYDRA.TODO :> TNil) :: Noodle.Inlets
type Outlets = TNil :: Noodle.Outlets
type InletsRow = (audio :: HYDRA.AudioSource, todo :: HYDRA.TODO)
type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "hide" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "hide" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "hide" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { audio: HYDRA.Silence, todo: HYDRA.TODO }

defaultO :: Record OutletsRow
defaultO = {}

defaultSt :: State
defaultSt = State unit

_in_audio = Noodle.Inlet :: _ "audio"
_in_todo = Noodle.Inlet :: _ "todo"

family :: Family
family = Family.make _hide defaultSt (Noodle.Shape :: Shape) defaultI defaultO hideP

makeNode :: Effect Node
makeNode = Family.spawn family

hideP :: Process
hideP = {- EMPTY PROCESS -}
    pure unit

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
