module INPUT.Test.Files.CodeGenTest.Hydra.Audio.SetSmooth where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: audio. Family :: setSmooth.

[[ : audio : setSmooth :: <audio:Audio {SIL} -> smooth:Value {N 0.4}> => <> ]] (#86) -}

_setSmooth :: NId.Family "setSmooth"
_setSmooth = NId.Family

type Inlets = (I "audio" Hot HYDRA.AudioSource :> I "smooth" Hot HYDRA.Value :> TNil) :: Noodle.Inlets
type Outlets = TNil :: Noodle.Outlets
type InletsRow = (audio :: HYDRA.AudioSource, smooth :: HYDRA.Value)
type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "setSmooth" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "setSmooth" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "setSmooth" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { audio: HYDRA.Silence, smooth: HYDRA.Number 0.4 }

defaultO :: Record OutletsRow
defaultO = {}

defaultSt :: State
defaultSt = State unit

_in_audio = Noodle.Inlet :: _ "audio"
_in_smooth = Noodle.Inlet :: _ "smooth"

family :: Family
family = Family.make _setSmooth defaultSt (Noodle.Shape :: Shape) defaultI defaultO setSmoothP

makeNode :: Effect Node
makeNode = Family.spawn family

setSmoothP :: Process
setSmoothP = {- EMPTY PROCESS -}
    pure unit

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
