module Test.Files.CodeGenTest.Hydra.Synth.Height where

import Prelude

import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW

{- Generated by Noodle Codegen from Hydra NDF file. -}

_height :: NId.Family "height"
_height = NId.Family

type Inlets = TNil :: Noodle.Inlets
type Outlets = (O "h" HT.Value :> TNil) :: Noodle.Outlets
type InletsRow = ()
type OutletsRow = (h :: HT.Value)
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "height" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "height" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "height" HW.WrapRepr InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = {}

defaultO :: Record OutletsRow
defaultO = { h: Error { source: "Height", error: "Expected space" } }

_out_h = Noodle.Outlet :: _ "h"

family :: Family
family = Family.make _height (HW.Value HT.None) (Noodle.Shape :: Shape) defaultI defaultO heightP

makeNode :: Effect Node
makeNode = Family.spawn family

heightP :: Process
heightP = pure unit
