module Test.Files.CodeGenTest.Input.Hydra.Synth.Hush where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import Hydra.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Hydra.Types as HT
import Hydra.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: synth. Family :: hush.

[[  synth : hush :: <> => <> ]] (#69) -}

_hush :: NId.Family "hush"
_hush = NId.Family

type Inlets = TNil :: Noodle.Inlets
type Outlets = TNil :: Noodle.Outlets
type InletsRow = ()
type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "hush" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "hush" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "hush" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = {}

defaultO :: Record OutletsRow
defaultO = {}

defaultSt :: State
defaultSt = State unit

family :: Family
family = Family.make _hush defaultSt (Noodle.Shape :: Shape) defaultI defaultO hushP

makeNode :: Effect Node
makeNode = Family.spawn family

hushP :: Process
hushP = {- EMPTY PROCESS -}
    pure unit

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
