module INPUT.Test.Files.CodeGenTest.Hydra.Synth.SetResolution where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HYDRAW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: synth. Family :: setResolution.

[[  synth : setResolution :: <width:Value {N 100.0} -> height:Value {N 100.0}> => <> ]] (#68) -}

_setResolution :: NId.Family "setResolution"
_setResolution = NId.Family

type Inlets = (I "width" Hot HYDRA.Value :> I "height" Hot HYDRA.Value :> TNil) :: Noodle.Inlets
type Outlets = TNil :: Noodle.Outlets
type InletsRow = (width :: HYDRA.Value, height :: HYDRA.Value)
type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "setResolution" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "setResolution" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "setResolution" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { width: HYDRA.Number 100.0, height: HYDRA.Number 100.0 }

defaultO :: Record OutletsRow
defaultO = {}

defaultSt :: State
defaultSt = State unit

_in_width = Noodle.Inlet :: _ "width"
_in_height = Noodle.Inlet :: _ "height"

family :: Family
family = Family.make _setResolution defaultSt (Noodle.Shape :: Shape) defaultI defaultO
  setResolutionP

makeNode :: Effect Node
makeNode = Family.spawn family

setResolutionP :: Process
setResolutionP = {- EMPTY PROCESS -}
    pure unit

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
