module FOOBAR.Test.Files.CodeGenTest.Input.Hydra.Synth.Speed where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HT
import HydraTk.Repr.Wrap as HW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: synth. Family :: speed.

[[  synth : speed :: <v:Value {N 1.0}> => <> ]] (#71) -}

_speed :: NId.Family "speed"
_speed = NId.Family

type Inlets = (I "v" Hot HT.Value :> TNil) :: Noodle.Inlets
type Outlets = TNil :: Noodle.Outlets
type InletsRow = (v :: HT.Value)
type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "speed" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "speed" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "speed" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { v: HT.Number 1.0 }

defaultO :: Record OutletsRow
defaultO = {}

defaultSt :: State
defaultSt = State unit

_in_v = Noodle.Inlet :: _ "v"

family :: Family
family = Family.make _speed defaultSt (Noodle.Shape :: Shape) defaultI defaultO speedP

makeNode :: Effect Node
makeNode = Family.spawn family

speedP :: Process
speedP = {- EMPTY PROCESS -}
    pure unit

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
