module INPUT.Test.Files.CodeGenTest.Hydra.Synth.Update where

import Prelude

import Data.Newtype (class Newtype)
import Effect (Effect)
import HydraTk.Repr.Wrap (WrapRepr(..))
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Repr.HasFallback (class HasFallback)
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import HydraTk.Types as HYDRA
import HydraTk.Repr.Wrap as HYDRAW
import Data.Tuple.Nested ((/\))

{- Generated by Noodle Codegen from Hydra NDF file. Group :: synth. Family :: update.

[[  synth : update :: <fn:UpdateFn> => <> ]] (#67) -}

_update :: NId.Family "update"
_update = NId.Family

type Inlets = (I "fn" Hot HYDRA.UpdateFn :> TNil) :: Noodle.Inlets
type Outlets = TNil :: Noodle.Outlets
type InletsRow = (fn :: HYDRA.UpdateFn)
type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
newtype State = State Unit
type Process = Noodle.Process State InletsRow OutletsRow WrapRepr Effect
type Node = Noodle.Node "update" State InletsRow OutletsRow WrapRepr Effect
type Family = Noodle.Family "update" State InletsRow OutletsRow WrapRepr Effect
type F = Noodle.F "update" State InletsRow OutletsRow WrapRepr Effect

defaultI :: Record InletsRow
defaultI = { fn: HYDRA.UpdateFn \ctx -> pure unit }

defaultO :: Record OutletsRow
defaultO = {}

defaultSt :: State
defaultSt = State unit

_in_fn = Noodle.Inlet :: _ "fn"

family :: Family
family = Family.make _update defaultSt (Noodle.Shape :: Shape) defaultI defaultO updateP

makeNode :: Effect Node
makeNode = Family.spawn family

updateP :: Process
updateP = {- EMPTY PROCESS -}
  pure unit

instance HasFallback State where
  fallback = defaultSt

derive instance Newtype State _
