module StarterTk.P5.Sketch where

import Prelude

import Demo.Toolkit.Starter.Repr.ChRepr (ValueRepr)
import Effect (Effect)
import Noodle.Fn.Process as Fn
import Noodle.Fn.Process as Noodle
import Noodle.Fn.Shape (I, O)
import Noodle.Fn.Shape as Noodle
import Noodle.Fn.Shape.Temperament (Cold, Hot)
import Noodle.Id as NId
import Noodle.Node as Noodle
import Noodle.Toolkit.Families as Noodle
import Noodle.Toolkit.Family as Family
import Noodle.Toolkit.Family as Noodle
import Type.Data.List (type (:>))
import Type.Data.List.Extra (TNil)
import Data.Tuple.Nested ((/\), type (/\))
import Demo.Toolkit.Starter.Repr.ChRepr as VR

{- Generated by Noodle Codegen from NDF file. Group :: p5. Family :: sketch.

[[  p5 : sketch :: <shape:Shape {s/circle} -> wavescount:Number {#/5.0} -> startcolor:Color {c/00000} -> endcolor:Color {c/143636} -> xspasing:Number {#/16} -> amplitude:Number {#/75} -> period:Number {#/500}> => <> ]] (#14) -}

_sketch :: NId.Family "sketch"
_sketch = NId.Family

type Inlets =
  ( I "shape" Hot VR.Shape :> I "wavescount" Hot Number :> I "startcolor" Hot VR.Color
      :> I "endcolor" Hot VR.Color
      :> I "xspasing" Hot Number
      :> I "amplitude" Hot Number
      :> I "period" Hot Number
      :> TNil
  ) :: Noodle.Inlets

type Outlets = TNil :: Noodle.Outlets
type InletsRow =
  ( shape :: VR.Shape
  , wavescount :: Number
  , startcolor :: VR.Color
  , endcolor :: VR.Color
  , xspasing :: Number
  , amplitude :: Number
  , period :: Number
  )

type OutletsRow = ()
type Shape = Noodle.Shape Inlets Outlets
type Process = Noodle.Process Unit InletsRow OutletsRow ValueRepr Effect
type Node = Noodle.Node "sketch" Unit InletsRow OutletsRow ValueRepr Effect
type Family = Noodle.Family "sketch" Unit InletsRow OutletsRow ValueRepr Effect
type F = Noodle.F "sketch" Unit InletsRow OutletsRow ValueRepr Effect

defaultI :: Record InletsRow
defaultI =
  { shape: VR.Circle
  , wavescount: 5.0
  , startcolor: VR.Color { r: 0, g: 0, b: 0, a: 255 }
  , endcolor: VR.Color { r: 0, g: 0, b: 0, a: 255 }
  , xspasing: 16.0
  , amplitude: 75.0
  , period: 500.0
  }

defaultO :: Record OutletsRow
defaultO = {}

_in_shape = Noodle.Inlet :: _ "shape"
_in_wavescount = Noodle.Inlet :: _ "wavescount"
_in_startcolor = Noodle.Inlet :: _ "startcolor"
_in_endcolor = Noodle.Inlet :: _ "endcolor"
_in_xspasing = Noodle.Inlet :: _ "xspasing"
_in_amplitude = Noodle.Inlet :: _ "amplitude"
_in_period = Noodle.Inlet :: _ "period"

family :: Family
family = Family.make _sketch unit (Noodle.Shape :: Shape) defaultI defaultO sketchP

makeNode :: Effect Node
makeNode = Family.spawn family

sketchP :: Process
sketchP = pure unit
